# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20170306_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Bank'),
        ),
    ]
